### データフレームの作成と保存
一般的な方法
1. 外部データソースからデータフレームを作成する:
    - Pandas は CSV、Excel、SQL データベースなど様々な外部データソースから直接データフレームを作成する機能を提供しています。
2. 辞書からデータフレームを作成する:
    - キーが列名、値がデータのリストまたは配列となる辞書を使って、データフレームを作成します。
3. リストのリストからデータフレームを作成する:
    - 内側のリストが行を表し、各リストが同じ長さである必要があります。列名は別途指定することができます。

In [ ]:
# カラム名をキー、データ列を値とした辞書より、DataFrameを作成

import pandas as pd

data = {
    '名前': ['相葉雅紀', '松本潤', '二宮和也', '大野智', '櫻井翔'],
    '出身': ['千葉', '東京', '東京', '東京', '東京'],
    '生年': [1982, 1983, 1983, 1980, 1982],
    '身長': [175, 172, 168, 166, 171],
    '血液型': ['AB', 'A', 'A', 'A', 'A'],
}
df = pd.DataFrame(data)



df.head() # 最初の5行を表示

     名前  出身    生年   身長 血液型
0  相葉雅紀  千葉  1982  175  AB
1   松本潤  東京  1983  172   A
2  二宮和也  東京  1983  168   A
3   大野智  東京  1980  166   A
4   櫻井翔  東京  1982  171   A

In [ ]:
# 列名のリストと、データ列のリストを用いて、DataFrameを作成

import pandas as pd

columns = ['名前', '出身', '生年', '身長', '血液型']
data = [
    ['相葉雅紀', '千葉', 1982, 175, 'AB'],
    ['松本潤', '東京都', 1983, 172, 'A'],
    ['二宮和也', '東京都', 1983, 168, 'A'],
    ['大野智', '東京都', 1980, 166, 'A'],
    ['櫻井翔', '東京都', 1982, 171, 'A'],
]
df = pd.DataFrame(data, columns=columns)

# 保存 csv
df.to_csv('./data/arashi.csv', index=False, encoding='utf_8_sig')

# 保存 excel
# df.to_excel('./data/arashi.xlsx')

In [34]:
import pandas as pd
df2 = pd.DataFrame({
    '名前': ['大野智', '相葉雅紀', '二宮和也', '松本潤', 'カビゴン'],
    '身長': [166, 176, 168, 173, 210],
    '体重': [52.0, 58.0, 52.0, 62.0, 460.0],
})

# 保存 csv
df2.to_csv('./data/arashi2.csv', index=False, encoding='utf_8_sig')

In [ ]:
# カラム列からデータ列を取り出す

import pandas as pd

columns = ['名前', '出身', '生年', '身長', '血液型']
data = [
    ['相葉雅紀', '千葉', 1982, 175, 'AB'],
    ['松本潤', '東京都', 1983, 172, 'A'],
    ['二宮和也', '東京都', 1983, 168, 'A'],
    ['大野智', '東京都', 1980, 166, 'A'],
    ['櫻井翔', '東京都', 1982, 171, 'A'],
]
df = pd.DataFrame(data, columns=columns)

# '名前'列のデータを取り出す
for name in df['名前']:
    print(name)

# '名前'列と'血液型'列のデータを同時に取り出す
for name, blood in zip(df['名前'], df['血液型']):
    print(name, blood)

相葉雅紀
松本潤
二宮和也
大野智
櫻井翔
相葉雅紀 AB
松本潤 A
二宮和也 A
大野智 A
櫻井翔 A

In [9]:
# データ列の追加

import pandas as pd

columns = ['名前', '出身', '生年', '身長', '血液型']
data = [
    ['相葉雅紀', '千葉', 1982, 175, 'AB'],
    ['松本潤', '東京都', 1983, 172, 'A'],
    ['二宮和也', '東京都', 1983, 168, 'A'],
    ['大野智', '東京都', 1980, 166, 'A'],
    ['櫻井翔', '東京都', 1982, 171, 'A'],
]
df = pd.DataFrame(data, columns=columns)

df['性別'] = ['男性', '男性', '男性', '男性', '男性']

df['年齢'] = 2022 - df['生年']

df.head() # 最初の5行を表示

     名前   出身    生年   身長 血液型  性別  年齢
0  相葉雅紀   千葉  1982  175  AB  男性  40
1   松本潤  東京都  1983  172   A  男性  39
2  二宮和也  東京都  1983  168   A  男性  39
3   大野智  東京都  1980  166   A  男性  42
4   櫻井翔  東京都  1982  171   A  男性  40

In [18]:
# n行目のデータを取り出す

import pandas as pd

columns = ['名前', '出身', '生年', '身長', '血液型']
data = [
    ['相葉雅紀', '千葉', 1982, 175, 'AB'],
    ['松本潤', '東京都', 1983, 172, 'A'],
    ['二宮和也', '東京都', 1983, 168, 'A'],
    ['大野智', '東京都', 1980, 166, 'A'],
    ['櫻井翔', '東京都', 1982, 171, 'A'],
]
df = pd.DataFrame(data, columns=columns)

print(df.iloc[0]) # 1行目のデータを取り出す
print()

print(df['出身'][0]) # '出身'列の1行目のデータを取り出す
print(df.iloc[0]['出身']) # '出身'列の1行目のデータを取り出す

名前     相葉雅紀
出身       千葉
生年     1982
身長      175
血液型      AB
Name: 0, dtype: object

千葉
千葉

### SQL風の操作
Pandas は、SQLスタイルのデータ操作を提供している。

In [20]:
# 射影 (PROJECTION)
# SQLのSELECT文に相当する操作

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')


df[['名前', '血液型']] # '名前'列と'血液型'列のデータを取り出す
# SELECT 名前, 血液型 FROM df

     名前 血液型
0  相葉雅紀  AB
1   松本潤   A
2  二宮和也   A
3   大野智   A
4   櫻井翔   A

In [ ]:
# 選択(selection)
# SQLのWHERE句に相当する操作

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')

# queryメソッドを用いて、身長が170以上のデータを取り出す
df.query('身長 >= 170')
# SELECT * FROM df WHERE 身長 >= 170

# bool indexingを用いて、身長が170以上のデータを取り出す
df[df['身長'] >= 170]


# 複数条件
# SELECT * FROM df WHERE 身長 >= 170 AND 血液型 == "A"
df.query('身長 >= 170 and 血液型 == "A"')
df[(df['身長'] >= 170) & (df['血液型'] == 'A')]

    名前   出身    生年   身長 血液型
1  松本潤  東京都  1983  172   A
4  櫻井翔  東京都  1982  171   A

In [ ]:
# グループ化と集約
# SQLのGROUP BY句に相当する操作

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')

for category, grouped in df.groupby('血液型'): # '血液型'列の値をカテゴリーとしてグループ化
    print(category) # カテゴリー(ここでは血液型)
    print(grouped)  # カテゴリーごとのデータフレーム

A
     名前   出身    生年   身長 血液型
1   松本潤  東京都  1983  172   A
2  二宮和也  東京都  1983  168   A
3   大野智  東京都  1980  166   A
4   櫻井翔  東京都  1982  171   A
AB
     名前  出身    生年   身長 血液型
0  相葉雅紀  千葉  1982  175  AB

In [ ]:
# グループ化と集約
# SQLのGROUP BY句に相当する操作

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')

# 血液型ごとに身長の要約統計量を計算する
df.groupby('血液型')['身長'].describe()

     count    mean       std    min    25%    50%     75%    max
血液型
A      4.0  169.25  2.753785  166.0  167.5  169.5  171.25  172.0
AB     1.0  175.00       NaN  175.0  175.0  175.0  175.00  175.0

### 表の連結

In [5]:
# 単純な連結

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')
df2 = pd.read_csv('./data/arashi2.csv')

pd.concat([df,df2])

# 横方向に連結
#pd.concat([df, df2], axis=1)

     名前   出身      生年   身長  血液型     体重
0  相葉雅紀   千葉  1982.0  175   AB    NaN
1   松本潤  東京都  1983.0  172    A    NaN
2  二宮和也  東京都  1983.0  168    A    NaN
3   大野智  東京都  1980.0  166    A    NaN
4   櫻井翔  東京都  1982.0  171    A    NaN
0   大野智  NaN     NaN  166  NaN   52.0
1  相葉雅紀  NaN     NaN  176  NaN   58.0
2  二宮和也  NaN     NaN  168  NaN   52.0
3   松本潤  NaN     NaN  173  NaN   62.0
4  カビゴン  NaN     NaN  210  NaN  460.0

In [7]:
# 表データのジョイン操作

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')
df2 = pd.read_csv('./data/arashi2.csv')

pd.merge(df,df2,on='名前')

     名前   出身    生年  身長_x 血液型  身長_y    体重
0  相葉雅紀   千葉  1982   175  AB   176  58.0
1   松本潤  東京都  1983   172   A   173  62.0
2  二宮和也  東京都  1983   168   A   168  52.0
3   大野智  東京都  1980   166   A   166  52.0

### ジョイン操作の方法
- 内部ジョイン inner: 両方にキーが存在するとき結合
- 外部ジョイン outer: どちらか一方にキーが存在するとき結合
- 左外部ジョイン left: 左側にキーが存在するとき
- 右外部ジョイン right: 右側にキーが存在するとき

#

In [10]:
# 表データのジョイン操作 Outer

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')
df2 = pd.read_csv('./data/arashi2.csv')


pd.merge(df, df2, on='名前', how='outer')

     名前   出身      生年   身長_x  血液型   身長_y     体重
0  カビゴン  NaN     NaN    NaN  NaN  210.0  460.0
1  二宮和也  東京都  1983.0  168.0    A  168.0   52.0
2   大野智  東京都  1980.0  166.0    A  166.0   52.0
3   松本潤  東京都  1983.0  172.0    A  173.0   62.0
4   櫻井翔  東京都  1982.0  171.0    A    NaN    NaN
5  相葉雅紀   千葉  1982.0  175.0   AB  176.0   58.0

### データフレームのソート

In [23]:
# 表データのジョイン操作 Outer

import pandas as pd

# csvファイルからDataFrameを作成
df = pd.read_csv('./data/arashi.csv')
df2 = pd.read_csv('./data/arashi2.csv')


df_merge=pd.merge(df, df2, on='名前', how='outer')

df_merge.sort_values(by='体重', ascending=False)

     名前   出身      生年   身長_x  血液型   身長_y     体重
0  カビゴン  NaN     NaN    NaN  NaN  210.0  460.0
3   松本潤  東京都  1983.0  172.0    A  173.0   62.0
5  相葉雅紀   千葉  1982.0  175.0   AB  176.0   58.0
1  二宮和也  東京都  1983.0  168.0    A  168.0   52.0
2   大野智  東京都  1980.0  166.0    A  166.0   52.0
4   櫻井翔  東京都  1982.0  171.0    A    NaN    NaN